### PR TITLE
fix, refactor(messenger): don't count muted chats, remove defunct workarounds

### PR DESCRIPTION
**Pull request by beerpiss**
### Description
- Fixes issue where muted chats in Facebook Messenger still count towards the badge count.
- Remove defunct workarounds (maybe except the `aria-label` workaround, but that one doesn't work unless the language is English)

### CODE REVIEW

**Comment by vraravam** [comment]
I don't use FB at all. I will request some other contributor to test these changes and then approve.

**Comment by vraravam** [comment]
@beerpiss - according to the documentation for contributing, please run the `pnpm run package` command. It should have raised an error that that package version has not been bumped up.

**Comment by mydarkstar** [comment]
Hey @beerpiss, thanks for your contribution!
Could you please review whether the current state works for you?
Since the recipe uses a lot of auto-generated classes currently, I'd like to make sure we don't merge anything broken. :)

**Comment by beerpiss** [comment]
> Hey @beerpiss, thanks for your contribution! Could you please review whether the current state works for you? Since the recipe uses a lot of auto-generated classes currently, I'd like to make sure we don't merge anything broken. :)

It currently works fine for me, muted channels aren't going through: 
image

**Comment by vraravam** [comment]
@all-contributors please add @beerpiss for code

**Comment by vraravam** [comment]
@all-contributors please add @mydarkstar  for code, review

**Pull request merged**
