### PR TITLE
add new recipe: Reclaim

### PR DESCRIPTION
**Pull request by matchcom-cahors**
https://reclaim.ai/

### CODE REVIEW

**Review by vraravam — CHANGES_REQUESTED** [review]
Please include the basic version of the `webview.js` file as created by the generator.

**Comment by matchcom-cahors** [comment]
✅ done

**Review by vraravam — APPROVED** [review]
LGTM - after CI checks pass.

**Comment by vraravam** [comment]
@all-contributors please add @matchcom-cahors for code.

**Comment by matchcom-cahors** [comment]
thank you @vraravam

**Pull request merged**
