### PR TITLE
Change name of Tutanota to Tuta Mail

### PR DESCRIPTION
**Pull request by noraj**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

tuta renamed and changed domain

image

image

### CODE REVIEW

**Review by mydarkstar — CHANGES_REQUESTED** [review]
Hi, thanks for the submission!
However, the `id` / `recipeId` has to stay the same, as otherwise this PR would be breaking the recipe already in use in clients.

Please don't rename the directory nor the `id` value in the package.json.
It may also be desirable to add an alias (`aliases`) for "Tutanota".

The Twitter / X PR can be used as a reference:
https://github.com/ferdium/ferdium-recipes/pull/423/files

**Review by vraravam — COMMENTED** [review]
based on #464 , has the icon changed as well?

**Comment by noraj** [comment]
> based on #464 , has the icon changed as well?

yes true, you can merge the duplicate PR with the icon

**Comment by mydarkstar** [comment]
> based on #464 , has the icon changed as well?

The logo and brand colors of Tuta have **not** changed, no. They just use the "lazy" method of dark mode and invert the colors.

However, I have noticed upon logging in, that the entire UI of this recipe is now branded "Tuta Mail".
The same goes for the GitHub repository and F-Droid app.

So it seems like that would be the most appropriate name.

**Review by mydarkstar — APPROVED** [review]

**Pull request merged**
