### PR TITLE
Add Excalidraw recipe

### PR DESCRIPTION
**Pull request by victorbnl**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Closes https://github.com/ferdium/ferdium-app/issues/1223

### CODE REVIEW

**Review by vraravam — CHANGES_REQUESTED** [review]
I dont think we should have 2 recipes for Excalidraw. Other than the `serviceURL`, what else is different?

**Comment by victorbnl** [comment]
Pretty much nothing for the recipe, but having only one recipe makes it harder for either free or paid users I think. Say we put as a default the URL of the free version, paid users will have to type in the URL manually.

**Comment by vraravam** [comment]
> paid users will have to type in the URL manually.

you can add a self-hosted option in the recipe's package.json for them to then configure it

**Comment by victorbnl** [comment]
They will still have to configure it manually.

Actually the best thing I’m thinking about is providing the package.json with an array of URLs and having Ferdium to ask which URL to use when configuring the service, but it would require changes in Ferdium as well.

**Comment by victorbnl** [comment]
Well I’ll make the free version the default one and add a self-hosted option.

**Review by vraravam — APPROVED** [review]

**Pull request merged**
