### PR TITLE
Telegram: Improve view width on 'K' version

### PR DESCRIPTION
**Pull request by danisztls**

### CODE REVIEW

**Review by vraravam — CHANGES_REQUESTED** [review]
@danisztls - according to the documentation for contributing, please run the `pnpm run package` command. It should have raised an error that that package version has not been bumped up.

**Comment by vraravam** [comment]
@danisztls - since a PR is usually grokked by search engines, and folks will land here based on these search results, could I request you to please add appropriate description and also a before and after images after applying your changes? I will approve and merge the PR anyways - but that is a request you can do even after I do so. TIA

**Comment by PlaceboPRS** [comment]
Is it possible to also fix the amount of space the messages themselves take up? In this fixed version (which is a great improvement!) there's no more deadspace on the sides but the actual messages are narrowly squashed into the middle versus version Z:


Version K:

image

Version Z:

image

**Comment by danisztls** [comment]
@PlaceboPRS https://github.com/ferdium/ferdium-recipes/pull/33

**Comment by vraravam** [comment]
The version bump was done in the wrong `package.json` - it should have been done in the one within the recipe folder - not at the global one. I too didn't notice it, and so this new version has not rolled into the latest nightly. I have made the corrections and it should trigger for tomorrow's nightly. Please make a note of this for future contributions. TIA

**Comment by danisztls** [comment]
@vraravam Sorry about that. The same mistake was made on the previous contribution. 😁

**Comment by vraravam** [comment]
Can you please point me to the other contribution? I'm unable to find it with your userid as the author

**Comment by vraravam** [comment]
np - found the other commit. tx

**Pull request merged**
