### PR TITLE
Add multiple recipes

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
This PR adds the following new services:
* Badoo
* Conceptboard
* Infomaniak Calendar
* Invoice Ninja
* Postman
* Regex101
* Revolt
* Strava
* Sympatia
* Temp Mail

This PR:
* closes ferdium/ferdium-app#1140
* closes ferdium/ferdium-app#1141
* closes ferdium/ferdium-app#1148
* closes ferdium/ferdium-app#1149
* closes ferdium/ferdium-app#1183
* closes ferdium/ferdium-app#1190
* closes ferdium/ferdium-app#1219
* closes ferdium/ferdium-app#1248
* closes ferdium/ferdium-app#1366
* closes ferdium/ferdium-app#1382

### CODE REVIEW

**Comment by mcmxcdev** [comment]
Awesome, working down the open issues in one sweep with a PR like this :smile: 

Unfortunately, I am pretty sure that a lot of these recipe requests will lead to follow up issues to change the URLs: From a quick check of e.g. Revolt Chat, I can see that the actual URL that people would probably want is https://app.revolt.chat/login rather than https://revolt.chat/

**Comment by SpecialAro** [comment]
> Awesome, working down the open issues in one sweep with a PR like this 😄
> 
> Unfortunately, I am pretty sure that a lot of these recipe requests will lead to follow up issues to change the URLs: From a quick check of e.g. Revolt Chat, I can see that the actual URL that people would probably want is https://app.revolt.chat/login rather than https://revolt.chat/

Thanks!

Yes, I think I missed that one (changed it on the wrong recipe and then forgot to add changes back) :p I'll correct it

**Comment by SpecialAro** [comment]
> > Awesome, working down the open issues in one sweep with a PR like this 😄
> > Unfortunately, I am pretty sure that a lot of these recipe requests will lead to follow up issues to change the URLs: From a quick check of e.g. Revolt Chat, I can see that the actual URL that people would probably want is https://app.revolt.chat/login rather than https://revolt.chat/
> 
> Thanks!
> 
> Yes, I think I missed that one (changed it on the wrong recipe and then forgot to add changes back) :p I'll correct it

I just checked and I have https://app.revolt.chat/ so I think everything is fine as it is 😯

**Comment by mcmxcdev** [comment]
Must've mistaken the url for the general website, my bad.

Also just checked all links, looks like you were thorough!

**Review by mcmxcdev — APPROVED** [review]

**Comment by SpecialAro** [comment]
> Must've mistaken the url for the general website, my bad.

No worries 😁 it's always good to double/triple check.. that's how problems are usually caught


> Also just checked all links, looks like you were thorough!

Thank you 🙏

**Pull request merged**
