### PR TITLE
adding a recipe for 'tick' (https://tickspot.com)

### PR DESCRIPTION
**Pull request by langdon**

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
Please fix the SVG icon size. Please run `pnpm package` to verify this locally.

**Review by vraravam — CHANGES_REQUESTED** [review]
Please fix the SVG icon size. Please run `pnpm package` to verify this locally.

**Comment by langdon** [comment]
huh, i swear i set the right size. /me checks

**Comment by langdon** [comment]
sorry about that, inkscape lied to me and i had too many containers running :)

**Review by vraravam — APPROVED** [review]
LGTM! (Haven't tested since i don't use this service)

**Comment by vraravam** [comment]
@all-contributors pls add @langdon for code

**Pull request merged**
