### PR TITLE
Add several recipes

### PR DESCRIPTION
**Pull request by SpecialAro**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I updated the version package [Updating](https://github.com/ferdium/ferdium-recipes/blob/main/docs/updating.md#4-updating-the-version-number) 

#### Description of Change

This PR adds 16 new recipes (fixing several recipe requests on the Ferdium-App issue board).

The added recipes are as follows:
- Mastodeck (fixes https://github.com/ferdium/ferdium-app/issues/959)
- Microsoft Planner (fixes https://github.com/ferdium/ferdium-app/issues/955)
- Alibaba Chat (fixes https://github.com/ferdium/ferdium-app/issues/1376)
- Fiverr (step forward in https://github.com/ferdium/ferdium-app/issues/1377 - missing unread logic)
- Draw.io (fixes https://github.com/ferdium/ferdium-app/issues/1429)
- Canva (fixes https://github.com/ferdium/ferdium-app/issues/1447)
- Penpot (fixes https://github.com/ferdium/ferdium-app/issues/1469)
- HackerNews (fixes https://github.com/ferdium/ferdium-app/issues/1505)
- Google Maps (fixes https://github.com/ferdium/ferdium-app/issues/1513)
- Patreon (fixes https://github.com/ferdium/ferdium-app/issues/1524)
- Fandom (fixes https://github.com/ferdium/ferdium-app/issues/1540)
- Romeo (fixes https://github.com/ferdium/ferdium-app/issues/1553)
- Infomaniak Kdrive (fixes https://github.com/ferdium/ferdium-app/issues/1559)
- Notion Calendar (fixes https://github.com/ferdium/ferdium-app/issues/1599)
- Superlist (fixes https://github.com/ferdium/ferdium-app/issues/1601)
- Purelymail (fixes https://github.com/ferdium/ferdium-app/issues/1624)
- SOGo (fixes https://github.com/ferdium/ferdium-app/issues/1472)

### CODE REVIEW

**Comment by SpecialAro** [comment]
Build failing possibly because I force pushed a commit (it shouldn't fail though...) - it is complaining about not version bump on alibaba-chat (which is impossible - the version bump action runs sucessfuly).

Lets wait a few for a new runner to re-trigger the build again to see if it fixes (probably has to do with cache on the runner side).

On the meantime if anyone cares to try and package locally, you would see that everything is fine:

**Review by mcmxcdev — APPROVED** [review]
Wow, thanks for another one of these recipe implementation sweeps!

The only thing that concerns me: we will close all these issues but most of these recipes don't have any notification functionality, so they don't do anything useful?

**Comment by SpecialAro** [comment]
> Wow, thanks for another one of these recipe implementation sweeps!

You're welcome 😁


> The only thing that concerns me: we will close all these issues but most of these recipes don't have any notification functionality, so they don't do anything useful?

That is true, yes... I only implemented notification sounds to those requests where users explicitly said it was a feature.. nevertheless I think that we can tackle those issues as they come or even gradually see what recipes have notifications and implement it pro-actively.

**Comment by mcmxcdev** [comment]
> That is true, yes... I only implemented notification sounds to those requests where users explicitly said it was a feature.. nevertheless I think that we can tackle those issues as they come or even gradually see what recipes have notifications and implement it pro-actively.

We can also rely on users adding in functionality for recipes as we go.

**Comment by NocturnalNick** [comment]
@SpecialAro 
Is login to Notion Calendar working? I can't figure out a way to log in, am I missing something

**Comment by SpecialAro** [comment]
@NocturnalNick it seems it is not working properly (login with Google is always a PITA). I'll try to find a workaround

**Comment by NocturnalNick** [comment]
> @NocturnalNick it seems it is not working properly (login with Google is always a PITA). I'll try to find a workaround

A million thanks for trying and even more if successful! Just wish I could auth with the authenticator app and a QR code or something.

**Comment by SpecialAro** [comment]
@NocturnalNick I just pushed a PR to fix this. It should be fixed in the latest nightly 😁

**Pull request merged**
