### PR TITLE
add recipe for Portainer

### PR DESCRIPTION
**Pull request by lzkill**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I updated the version package [Updating](https://github.com/ferdium/ferdium-recipes/blob/main/docs/updating.md#4-updating-the-version-number) 

#### Description of Change

This PR adds a recipe for Portainer (see [https://www.portainer.io/](https://www.portainer.io/)).

### CODE REVIEW

**Review by mcmxcdev — APPROVED** [review]
LGTM, thank you :rocket:

**Comment by vraravam** [comment]
This PR is causing the build to fail - since the formatting hasn't been adhered to. @lzkill - please follow the contributing guidelines while submitting PRs.

**Comment by mcmxcdev** [comment]
> This PR is causing the build to fail - since the formatting hasn't been adhered to. @lzkill - please follow the contributing guidelines while submitting PRs.

Strange, the build was passing green for this PR.

**Comment by vraravam** [comment]
> Strange, the build was passing green for this PR.

The CI workflow for the recipes repo might not be verifying that formatting has been missed - if so, we need to add that verification in it.

What's even stranger is that the build of the main app for mac and linux passed this morning, but windows build bombed out (https://github.com/ferdium/ferdium-app/actions/runs/7719440896). Maybe the workflow code is inconsistent across the 3 OSes?

**Pull request merged**
