### PR TITLE
Add Gitea recipe

### PR DESCRIPTION
**Pull request by Flying--Dutchman**
Adds a Gitea recipe with notification support

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
Thanks for the contribution @Flying--Dutchman !

**Comment by vraravam** [comment]
@all-contributors please add @Flying--Dutchman for code

**Review by vraravam — CHANGES_REQUESTED** [review]
@Flying--Dutchman - please fix the errors that the CI build has flagged.

**Comment by Flying--Dutchman** [comment]
Ah my bad, sorry. Very strange, I thought I simply copied one of the `package.json` files.

**Review by vraravam — APPROVED** [review]

**Pull request merged**
