### PR TITLE
feat: add memos recipe

### PR DESCRIPTION
**Pull request by lincolnthalles**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

Add recipe for [memos](https://github.com/usememos/memos)

### CODE REVIEW

**Comment by SpecialAro** [comment]
Hi @lincolnthalles ! 

Thank you for logging this PR 😁

Just to clarify:
* Memos is self-hosted only, right? Meaning there is no "official" app rather than the demo?

If that is the case then let me suggest trying to change the `package.json` to something like the `Slack` recipe (that includes teamId and the teamIdSuffix). Can we test if making teamIdSuffix empty and the URL the full teamId works?

This way users will be forced to indicate a URL. Otherwise, if that doesn't work, we can keep it like is 😁

Let me know if you prefer that I test my suggestion on my side first!

**Comment by lincolnthalles** [comment]
> Hi @lincolnthalles !
> 
> Thank you for logging this PR 😁
> 
> Just to clarify:
> 
> * Memos is self-hosted only, right? Meaning there is no "official" app rather than the demo?
> 
> If that is the case then let me suggest trying to change the `package.json` to something like the `Slack` recipe (that includes teamId and the teamIdSuffix). Can we test if making teamIdSuffix empty and the URL the full teamId works?
> 
> This way users will be forced to indicate a URL. Otherwise, if that doesn't work, we can keep it like is 😁
> 
> Let me know if you prefer that I test my suggestion on my side first!

It's self-hosted only, the domain can be anything. So, there's no point in using the subdomain template from Slack.
By just removing `serviceURL` Ferdium will require user to input a URL.

**Comment by mcmxcdev** [comment]
Thanks for the added recipe @lincolnthalles !

**Comment by Alphrag** [comment]
@all-contributors please add @lincolnthalles for code

**Pull request merged**
