### PR TITLE
add new recipe: GamingOnLinux

### PR DESCRIPTION
**Pull request by fschaupp**
add webview scraping message & notification count

### CODE REVIEW

**Review by vraravam — CHANGES_REQUESTED** [review]
Where are the other files that are requires for the recipe to work?

**Comment by fschaupp** [comment]
I just added the webview to the existing recipe.
Is such an update usually done in a new PR or somehow on the old, closed one?

**Comment by vraravam** [comment]
Did you run the `pnpm run package` task? Please see the relevant documentation.

**Comment by vraravam** [comment]
Whenever any recipe changes, at a minimum, the recipe's `package.json` needs to change the `version` value.

**Review by vraravam — CHANGES_REQUESTED** [review]
When changing an existing recipe - you will need to ensure that the corresponding `package.json` file has the version bump. Please add that into this PR before it can be approved

Also, please squash all the commits in this PR branch and rebase from the latest master branch before this PR can be reviewed once more.

**Pull request closed without merging**
