### PR TITLE
Update Messenger link handling

### PR DESCRIPTION
**Pull request by Arthur-Huan**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

### CODE REVIEW

**Comment by mcmxcdev** [comment]
I am not using FB Messenger so I am unable to review this PR unfortunately. Can anyone else from @ferdium/reviewers jump in and verify?

**Comment by mjeveritt** [comment]
I wonder if, whilst we're in this area, we can somehow filter out where FB injects tracking elements into links, and/or a pre-check link that sends you first to messenger.com before the real link ? I've seen a few scripts/plugins that do this elsewhere .. but is it something that is worth incorporating in Ferdium too?
Perhaps it's an option that could be toggled on/off ?! (possibly default Off, to avoid whining!)

**Comment by mcmxcdev** [comment]
@mjeveritt Feel free to open an issue for it in https://github.com/ferdium/ferdium-app, then that feature be prioritized. 

It shouldn't extend the scope of the current PR.

**Review by Alphrag — APPROVED** [review]
Finally got around testing it, and it works well, thanks!

**Pull request merged**
