### PR TITLE
Fix Discord badge counts

### PR DESCRIPTION
**Pull request by Cknight70**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Discord numbered unread message badges as well as all new message badge is currently not working. This will fix both of these issues. As discussed here https://github.com/ferdium/ferdium-app/issues/1370

### CODE REVIEW

**Comment by Cknight70** [comment]
Hi, I'm not sure why its failing the check, but you can see files changed that I have changed the version number. I've been using ferdium with these changes and it works without issues, thanks.

**Review by mydarkstar — APPROVED** [review]

**Comment by mydarkstar** [comment]
@all-contributors please add @Cknight70 for code

**Comment by nerdCopter** [comment]
Thank you you for fixing it!

It would be my preference not to see this blue circle. i do not like it.
image

If it is not part of your PR, then my apologies.

**Comment by Cknight70** [comment]
@nerdCopter that is indicating indirect unread messages, which you can turn off by turning off notifications for all messages in that discord's settings

**Pull request merged**
