### PR TITLE
Add Gather service

### PR DESCRIPTION
**Pull request by victorbnl**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change

I added the [Gather](https://www.gather.town/) service, closes https://github.com/ferdium/ferdium-app/issues/1132.

### CODE REVIEW

**Comment by victorbnl** [comment]
Is it normal that the version bump check fails even though I added a new service?

**Comment by Alphrag** [comment]
It shouldn't be the case, but there seems to be a problem when we add a new service with the action we're using that only checks against the last commit instead of the diff between the PR branch and the head of the target where it can't find the file. 
I am not sure yet exactly where it is coming from (thinking of two different points) but this can be verified locally for now.

**Comment by Alphrag** [comment]
It shouldn't be the case, but there seems to be a problem when we add a new service with the action we're using that only checks against the last commit instead of the diff between the PR branch and the head of the target where it can't find the file. 
I am not sure yet exactly where it is coming from (thinking of two different points) but this can be verified locally for now.

**Comment by victorbnl** [comment]
Alright then!

**Pull request merged**
