### PR TITLE
Update Tutanota to new branding

### PR DESCRIPTION
**Pull request by rdwz**
- Update icon

[#1445](https://github.com/ferdium/ferdium-app/issues/1445)
https://github.com/ferdium/ferdium-recipes/pull/464#issuecomment-1837118458

### CODE REVIEW

**Comment by mcmxcdev** [comment]
I took a look at the website, and it seems we do use the wrong icon color currently. Thanks for the update!

Please bump the version in tutanota package.json, so that changes will be downloaded for the users once we merge this.

**Comment by rdwz** [comment]
> I took a look at the website, and it seems we do use the wrong icon color currently. Thanks for the update!

Where exactly did you look? 

tutamail

**Comment by victorbnl** [comment]
I think you misread @mcmxcdev’s comment. They actually confirm that the icon in use is wrong and should be updated according to your PR. So you just need to bump the recipe’s version and it will be likely to be accepted.

**Comment by rdwz** [comment]
> r PR. So you just need to bump t

Oops... I need to clean my glasses. 😅

**Comment by mcmxcdev** [comment]
Thanks for clarifying it Victor. Yes all looks good, will get it merged asap ;)

**Pull request merged**
