### PR TITLE
Update counter for Telegram webZ

### PR DESCRIPTION
**Pull request by CiteopehtEripmav**
Fixes Telegram WebZ/A not showing unread counters.

### CODE REVIEW

**Comment by victorbnl** [comment]
It works on my side for both direct and indirect counters. You just forgot to bump the recipe’s version number. Please see my pull request on your repository.

**Comment by CiteopehtEripmav** [comment]
Sorry, I made the description a bit too general. Inside the Telegram window, everything worked fine, but I never got the counter badge on Ferdium's vertical/horizontal bar. It wasn't until I went directly to Telegram website that I noticed the object name for Badge had changed to ChatBadge, so I decided to give it a try inside my Ferdium installation and it started working. Not sure if OS related, so, just in case, I'm running Ferdium 6.4.1-nightly.8 on x64 Windows 11 22H2 (22621.1992).

**Comment by victorbnl** [comment]
Don’t worry your description is just fine, now you have but to wait for developers to review your PR and it should be soon merged.

**Comment by Alphrag** [comment]
@CiteopehtEripmav thanks for the fix, that is indeed not something that will be OS specific since it is a change on the webapp itself :-) Since @victorbnl has tested the change locally and everything looks fine for me too, I'm happy to merge it.
As an additional note for the next time you'll make a PR: please make sure to make a name that is more specific for the service used, and to use the automatic template when creating a PR.

**Review by Alphrag — APPROVED** [review]

**Comment by Alphrag** [comment]
@all-contributors please add @CiteopehtEripmav for code

**Pull request merged**
