### PR TITLE
Allow gchat login page

### PR DESCRIPTION
**Pull request by iconeb**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

#### Description of Change
Add reference to workspace.google.com to redirect to login page, similar to other google services like Calendar and Mail

### CODE REVIEW

**Review by SpecialAro — CHANGES_REQUESTED** [review]
Tested and LGTM!

@iconeb, would you please bump the package.json version to 1.8.0 ? This way, users will be notified to upgrade to the new recipe version.

 Thank you very much!

**Comment by SpecialAro** [comment]
Also, I think this issue closes https://github.com/ferdium/ferdium-app/issues/1323

**Comment by SpecialAro** [comment]
@vraravam looks like the build is failing but the version bump is ok. I dont see any errors on my local when running `pnpm package`... Should we merge?

image

**Comment by vraravam** [comment]
yes, this kind of flakiness has occurred in the past. lets merge

**Comment by vraravam** [comment]
Linter found some issues - I have added a new commit to this PR

**Comment by vraravam** [comment]
@all-contributors - please add @iconeb for code

**Pull request merged**
