### PR TITLE
Renamed Twitter recipe to X. Added a new icon & updated package.json

### PR DESCRIPTION
**Pull request by hafiz-muhammad**
#### Pre-flight Checklist

Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.

### CODE REVIEW

**Review by mcmxcdev — APPROVED** [review]
LGTM!

Same question here for @vraravam: Do you think we can simply change a recipe name and id and ensure that users pull the latest changes to it correctly?

**Comment by vraravam** [comment]
> LGTM!
> 
> Same question here for @vraravam: Do you think we can simply change a recipe name and id and ensure that users pull the latest changes to it correctly?

Renaming a recipe will mean that further updates (including this one) will NOT make it into the user's installation folder. They will have to manually delete the older installed / configured service, and re-add/re-configure it.
To circumvent this is why I had implemented the alias, but that's a poor substitute at best.

**Comment by hafiz-muhammad** [comment]
I will close the pull request then.

**Comment by mcmxcdev** [comment]
@vraravam Can we not just simply keep the id of the recipe as „twitter“ to be backwards compatible but change the name and logo?

**Comment by SpecialAro** [comment]
> @vraravam Can we not just simply keep the id of the recipe as „twitter“ to be backwards compatible but change the name and logo?

Yes that is possible like so. Recipes are updated by ID

**Comment by mcmxcdev** [comment]
@hafiz-muhammad can you push another commit which makes sure the folder structure stays the same for „twitter“ but the logo and name is updated to X? Then we could merge this PR ;)

**Comment by vraravam** [comment]
If a new nightly has been created based on this "incorrect" change, we should at least delete it so that it doesn't get published @mcmxcdev

**Comment by hafiz-muhammad** [comment]
> @hafiz-muhammad can you push another commit which makes sure the folder structure stays the same for „twitter“ but the logo and name is updated to X? Then we could merge this PR ;)

I will do that.

**Comment by hafiz-muhammad** [comment]
I've made the changes.

**Comment by mcmxcdev** [comment]
@hafiz-muhammad please add one last commit and update the `package.json` to the following:

```
{
  "id": "twitter",
  "name": "X",
  "version": "1.4.1",
  "license": "MIT",
  "aliases": [
    "Twitter"
  ],
  "config": {
    "serviceURL": "https://x.com",
    "hasNotificationSound": true
  }
}

```

Then we can get this merged ;)

**Comment by hafiz-muhammad** [comment]
> @hafiz-muhammad please add one last commit and update the `package.json` to the following:
> 
> ```
> {
>   "id": "twitter",
>   "name": "X",
>   "version": "1.4.1",
>   "license": "MIT",
>   "aliases": [
>     "Twitter"
>   ],
>   "config": {
>     "serviceURL": "https://x.com",
>     "hasNotificationSound": true
>   }
> }
> ```
> 
> Then we can get this merged ;)

@mcmxcdev I've applied the requested changes.

**Pull request merged**
